### ISSUE TITLE
Any plans to implement with GTM?

### ISSUE THREAD

**Issue by grahamyesfit** [hudovisk/react-optimize#2]
Do you have any plans to [support GTM](https://support.google.com/optimize/answer/6314801?hl=en&ref_topic=6197443) in this library? Our React App uses GTM, so it would be awesome.

**Comment by hudovisk** [comment]
I am not sure, but I think it should work with GTM without problems. The only difference I see is the initialization snippet that you wouldn't need. Please let me know if you tried it and had any errors.

**Comment by albertkai** [comment]
Does not work, because `window.gtag` is used to update variant

**Comment by albertkai** [comment]
you can make that work by adding `window.gtag = function() { dataLayer.push(arguments) }` after the initialisation of GTM
