### ISSUE TITLE
Typescript - types definitions include into next version

### ISSUE THREAD

**Issue by progresak** [hudovisk/react-optimize#217]
Hey, first I would like to thank you for this library, a good job.

I have a question. I saw, that in the source code you introduced the `src/index.d.ts` file with the declaration of `react-optimize` module and types. 

Unfortunately, we're using your library in typescript and there is an import issue with types. Would it be possible to make types public in the next version for typescript to work out of the box?

![image](https://user-images.githubusercontent.com/4807925/97332747-1b1f1d00-187b-11eb-8147-55df025bbbf5.png)
```ts
TS7016: Could not find a declaration file for module 'react-optimize'. '/.../node_modules/react-optimize/lib/react-optimize.js' implicitly has an 'any' type.
  Try `npm install @types/react-optimize` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-optimize';
```
Or should I contribute to [`DefinitelyTyped` repo](https://github.com/DefinitelyTyped/DefinitelyTyped) and create types externally?

Thanks :-)

**Comment by hudovisk** [comment]
Thanks @progresak for pointing that out. I believe we can use something like [copy plugin for webpack](https://webpack.js.org/plugins/copy-webpack-plugin/) and copy the type declaration file into `lib/` until we move the library into typescript.

**Comment by progresak** [comment]
@hudovisk Thank you for quick response and solution 👍🏻
