### ISSUE TITLE
ReferenceError: window is not defined, when renering on server

### ISSUE THREAD

**Issue by Nazar32** [hudovisk/react-optimize#26]
Hi, I am getting this error, while rendering an experiment on server side
![image](https://user-images.githubusercontent.com/16920168/72431594-e5062600-379d-11ea-8aa9-7071b2f91ad7.png)

**Comment by hudovisk** [comment]
Hi, can you share what version of the library are you using? Or a repo where we can reproduce the error.

**Comment by Nazar32** [comment]
![image](https://user-images.githubusercontent.com/16920168/72609618-144b9d00-392e-11ea-9bd3-755ea03c8388.png)
Sorry, can not share the repository, because it is private.

**Comment by Nazar32** [comment]
Got it fixed by creating wrapper component over base `Experiment` and `Variant`, which just renders 
children on the server:
 
```
export const Experiment = ({ ...props }) => {
  if (!process.env.BROWSER) {
    return props.children;
  }
  const { Experiment: ReactOptimizeExperiment } = require('react-optimize');
  return (
    <ReactOptimizeExperiment {...props}/>
  );
};

Experiment.propTypes = {
  children: PropTypes.node.isRequired,
};

export const Variant = ({ ...props }) => {
  if (!process.env.BROWSER) {
    if (props.id === '0') {
      return props.children;
    }
    return null;
  }
  const { Variant: ReactOptimizeVariant } = require('react-optimize');
  return (
    <ReactOptimizeVariant {...props}/>
  );
};
```

**Comment by hudovisk** [comment]
I see, can you share what framework are you using to render on the server side?

**Comment by Nazar32** [comment]
![image](https://user-images.githubusercontent.com/16920168/72612981-02bac300-3937-11ea-97c1-7f4f2e0ecca8.png)
![image](https://user-images.githubusercontent.com/16920168/72612994-0c442b00-3937-11ea-8048-bac6fcd582ba.png)

**Comment by pjaws** [comment]
I just installed this package and tried to use it in Next.js, and I'm also seeing this error. My test page is pretty simple:

```
import React from 'react';
import { Experiment, Variant } from 'react-optimize';
import Layout from '../layouts/minimal';
import Head from '../components/head';

const AbTest = () => {
  return (
    <Layout>
      <Head url={`${process.env.HI_BASE_URL}/ab-test`} />
      <Experiment id={process.env.OPTIMIZE_EXP_ID}>
        <Variant id="0">This is the original variant.</Variant>
        <Variant id="1">This is variant B</Variant>
      </Experiment>
    </Layout>
  );
};

export default AbTest;
```

I was able to get around the window not defined issue by using `next/dynamic` and setting `ssr: false`: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr. However, the proper variant is not being loaded. I'll make a separate ticket for that, since it might be unrelated to this issue.

**Comment by hudovisk** [comment]
Thanks for providing a simple test case, I was able to reproduce and find out why this is happening. It is an issue with webpack umd modules: https://github.com/webpack/webpack/issues/6784

**Comment by pjaws** [comment]
Awesome! We decided to switch to server-side experiments for other reasons, but if we move back to client-side, I'll definitely use this library again 😁
