### ISSUE TITLE
Question: Why not have a default variant? ( for testing ) 

### ISSUE THREAD

**Issue by hugocruz** [hudovisk/react-optimize#32]
Hi, first of all, I find this library very useful. 
I was wondering do you not load a variant by default. 
The reasoning behind my question is that while testing something within a variant, it is quite tricky to set the variant then, so in `jest` for instance it is hard to assert somethign like a button that is inside the variants, making testing a quite simple library, quite complex. If there was an attribute like `default`, that would simplify things, or maybe you had other use cases in mind when you implemented it.

**Comment by hugocruz** [comment]
OK, 

I just got this, but to be honest the loader attribute was not very intuitive. :)

Anyhow, you may close this issue, sorry for the noise.

**Comment by philgruneich** [comment]
What is the "loader" attribute?
