### ISSUE TITLE
Question: compatible with server rendering?

### ISSUE THREAD

**Issue by perenstrom** [hudovisk/react-optimize#4]
Hi!

Is this compatible with server rendering? The google optimize integration does not exist when rendering on the server I presume, so will the client hydration then overwrite the server rendered? Which alternative will be the default when it doesn't find the experiment on the server?

Thanks.

**Comment by hudovisk** [comment]
You are correct, when server rendering you can use the `loader` prop in the `Experiment` component to render a loading component while the client side fetches the experiment. In any case, when we can't find the experiment the original variant (id = "0") is used.

**Comment by perenstrom** [comment]
Thank you!
