### ISSUE TITLE
Getting window is undefined on ssr

### ISSUE THREAD

**Issue by intelcoder** [hudovisk/react-optimize#6]
Should we check 

typeof window !== 'undefined' ?

**Comment by nuclearspike** [comment]
Something definitely needs to be done, even just importing/requiring the package will break an SSR app.

**Comment by hudovisk** [comment]
merged in [v2.2.0](https://github.com/hudovisk/react-optimize/releases/tag/v2.2.0). Thanks for the support!

**Comment by Nazar32** [comment]
Hi, I am getting this error, while rendering an experiment on server side
![image](https://user-images.githubusercontent.com/16920168/72431594-e5062600-379d-11ea-8aa9-7071b2f91ad7.png)
