### ISSUE TITLE
Doesn't have a fallback for cases where Google Optimize fails to load within a few seconds

### ISSUE THREAD

**Issue by dobesv** [hudovisk/react-optimize#9]
If Google Optimize fails to load and initialize within a few seconds, then the app should forge ahead with the first variant.

Currently it seems like it will just wait forever.

**Comment by jesperume** [comment]
Hi, 
This is a big issue for us. I see that there is a patch available. When will it be merged to master?

You can reproduce this by adding the following to your hosts file:
127.0.0.1 www.googletagmanager.com

Best Regards

**Comment by dobesv** [comment]
What we have done is to adopt a package called `patch-package` which applies patches to `node_modules` as a `postinstall` hook.  This lets us keep a temporary fork of projects while we wait for them to be patched.  Not ideal but a number of packages we use don't get super active maintenance, this one included.  The maintainers are volunteers after all, we can't complain about their work schedule when we don't pay them for it.

**Comment by hudovisk** [comment]
merged in [v2.2.0](https://github.com/hudovisk/react-optimize/releases/tag/v2.2.0). Thanks for the support!
